repos:
  - repo: local
    hooks:
      - id: run-tests-before-push
        name: Run tests with Pytest before push
        entry: poetry run pytest
        language: system
        stages: [push]
        pass_filenames: false
